# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-29 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='time',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
