# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-30 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_calendar_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=10)),
                ('time', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Car2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=10)),
                ('time', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
