# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-07 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20170430_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=10)),
                ('dog', models.TextField(default='', max_length=10)),
                ('total', models.FloatField(default='', max_length=10)),
                ('service', models.TextField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=1000)),
                ('day', models.CharField(default='', max_length=10)),
                ('time', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
